### ISSUE TITLE
Any plans to release to hackage?

### ISSUE THREAD

**Issue by alang9** [acowley/concurrent-machines#1]

**Comment by acowley** [comment]
I'd like to hear from someone else using it, or add some more tests. Have you tried it out?

**Comment by alang9** [comment]
Not very much. I essentially implemented `Data.Machine.Concurrent.Wye` before realizing that you had already done it.

**Comment by acowley** [comment]
That's a pretty good reason to release it on hackage. There was a suggestion to rename it `machines-concurrent`, what do you think about that? Does the concurrent `Wye` work as you expected?

**Comment by alang9** [comment]
Yep, `Data.Machine.Concurrent.Wye` works as expected and also looks right from looking at the code. I don't have a strong opinion about the name. `machines-concurrent` and `concurrent-machines` both seem like good names. `machines-async` and `async-machines` are other possibilites.

**Comment by acowley** [comment]
I updated for GHC 7.10 compatibility and pushed to hackage. Thanks for the interest and feedback!
