### ISSUE TITLE
'buffer' and 'rolling' don't fill their buffers

### ISSUE THREAD

**Issue by bens** [acowley/concurrent-machines#5]
I've done some graphing of processes using `buffer` and `bufferConnect` and noticed some strange behaviour.

`source [1..32] ~> bufferConnect 5 (worker (*2) 1 2) (worker id 2 4)`

![buffering1-par splot](https://cloud.githubusercontent.com/assets/37969/22853631/e4d8ad48-f0af-11e6-9773-d9f86f173c20.png)

So `bufferConnect` does what I'd expect which is run as much as it can until it's got 5 items buffered, and then only run when downstream takes an item.

`source [1..32] ~> buffer 5 (worker (*2) 1 2) ~> worker id 2 4`

![buffering2-par splot](https://cloud.githubusercontent.com/assets/37969/22853593/ff7aeb30-f0ae-11e6-9b8c-b8c16ad42758.png)

But `buffer` doesn't seem to do the same, it only buffers one item and waits until it empties completely before a new item is forced, which makes downstream wait.  The same difference exists between `rollingConnect` and `rolling` too.

`source [1..32] ~> rollingConnect 5 (worker (*2) 1 2) (worker id 2 4)`

![rolling1-par splot](https://cloud.githubusercontent.com/assets/37969/22853614/8accf570-f0af-11e6-9968-1cddfb1c810f.png)

`source [1..32] ~> rolling 5 (worker (*2) 1 2) ~> worker id 2 4`

![rolling2-par splot](https://cloud.githubusercontent.com/assets/37969/22853619/9bd3e5e0-f0af-11e6-9408-c6e2a9b7f238.png)

`worker` takes a function `a -> b`, an id number, and a delay for `threadDelay`, so nothing special.

(Plots were done with [splot](https://hackage.haskell.org/package/splot)).

**Comment by acowley** [comment]
I'll try to look into this, but can you give a quick go using the `>~>` combinator?

**Comment by acowley** [comment]
Actually, I would appreciate it if you could make the test case available somewhere so I can try to add it as a test suite. There is one very basic check that things are happening in parallel in the test suite, but more would be better.

**Comment by bens** [comment]
Using `>~>` adds a bit more parallelism, but still doesn't make the two match.  I've more or less rewritten the AllTests.hs file but feel free to take what you like from it: https://gist.github.com/bens/cc146d72bb2707082597abd461895036
I've added `process` as a dependency in the cabal file for tests as well.

**Comment by acowley** [comment]
I'm not sure if these can be fixed :/ The `*Connect` versions seem workable, but the issue is that we want `buffer n src ~> snk` to be able to become an `Await` several times *without evaluating* `snk`. The basic `~>` operator will evaluate the downstream value (`snk`) first, which is no good for us. The `>~>` operator will evaluate both in parallel, but if upstream `Yield`s, then it has nowhere to put the yielded value so it waits on downstream. `bufferConnect` is a replacement for those arrows, providing an opportunity to interpose the buffer.

Unless I'm missing something there, I'll cut a new release that removes `buffer` and `rolling`. Does that sound right to you?

**Comment by bens** [comment]
Yeah, I agree that if they can't work correctly they shouldn't be there.  Thanks for looking into it @acowley.  Would you like me to put the changed tests up as a pull request?

**Comment by acowley** [comment]
That would be great, but I think the requirement of having `splot` available should be disabled by default. We could probably use a package flag in the Cabal file and an `#ifdef` in the code to guard things.

**Comment by acowley** [comment]
I lost track of this on my TODO items, but it's uploaded now. I put a test that uses `splot` behind a cabal flag so the `cairo` dependency won't be there unless someone asks for it.

Thank you again for the help!

**Comment by bens** [comment]
Ah thanks, I was going to get to this but I've been moving house and so forth, thanks for finishing it up.
