### ISSUE TITLE
Is there a reason why base < 4.10 is a hard constraint?

### ISSUE THREAD

**Issue by kozross** [acowley/concurrent-machines#8]
This is a bit odd, and makes it somewhat difficult to combine with other stuff I enjoy (such as protolude-0.2 and the Stack nightlies). What's the reason for this choice?

**Comment by acowley** [comment]
It is not a hard constraint, merely an overly conservative upper bound. There is an open issue on the library that I haven't resolved yet that I'd really like to fix, but I'll fix the bounds (or you can PR it) as soon as I get a chance.
